name: Deploy to Firebase
on:
  push:
    branches:
      - master
      - dev

jobs:
  firebase-build:
    name: Firebase Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set branch environments
        run: |-
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
             echo "CMD=deploy-prod" >> "$GITHUB_ENV"
          fi
          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
             echo "CMD=deploy-dev" >> "$GITHUB_ENV"
          fi
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Build and deploy
        run: npm run ${{ env.CMD }}
        env:
          CI: ''
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
