name: Firebase hosting

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install firebase tools
      run: |
        sudo npm install -g firebase-tools
        firebase use test-ci-cd-automation --token ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Build website
      run: |
        npm i
        npm run build
        
    - name: Deploy to staging site
      if: github.ref == 'refs/heads/main'
      run: firebase deploy --only hosting:prod --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"
      
    - name: Deploy to production site
      if: github.ref == 'refs/heads/dev'
      run: firebase deploy --only hosting:dev --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"

    - name: Archive build Artifact
      uses: actions/upload-artifact@master
      with:
        path: build
