name: Deploy to Asset-Management Project
on:
  push:
    branches:
      - main
jobs:
 deploy_asset_management_website:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Install Dependencies
       run: |
          npm i
          npm i -g firebase-tools
     - name: Build App
       run: |
         npm run build
     - uses: FirebaseExtended/action-hosting-deploy@v0
       with:
         repoToken: '${{ secrets.GITHUB_TOKEN }}'
         firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
         channelId: test-ci-cd-automation
         projectId: "${{ secrets.FIREBASE_ID }}"