name: Deploy to project
on:
  push:
    branches:
      - main
jobs:
 deploy_asset_management_website:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Install Dependencies
       run: |
          npm i
          npm i -g firebase-tools
     - name: Build App
       run: |
         npm run build
     - uses: FirebaseExtended/action-hosting-deploy@v0
       with:
         repoToken: '${{ secrets.GITHUB_TOKEN }}'
         firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
         channelId: live
         projectId: "${{ secrets.FIREBASE_ID }}"

# name: Build and Deploy
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@master
#       - name: Install Dependencies
#         run: npm install
#       - name: Build
#         run: npm run build
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

# name: Firebase hosting

# on:
#   push:
#     branches: [ main, dev]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     - name: Install firebase tools
#       run: |
#         npm install -g firebase-tools
#         firebase use ${{ secrets.FIREBASE_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        
#     - name: Build website
#       run: |
#         npm i
#         npm run build
        
#     - name: Deploy to staging site
#       if: github.ref == 'refs/heads/dev'
#       run: firebase deploy --only hosting:dev --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"
      
#     - name: Deploy to production site
#       if: github.ref == 'refs/heads/main'
#       run: firebase deploy --only hosting:prod --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"

#     - name: Archive build Artifact
#       uses: actions/upload-artifact@master
#       with:
#         path: build